# Generated by Django 4.0.5 on 2022-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usd_price', models.IntegerField()),
                ('rub_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
